str=input("Enter a string: ")
length=len(str)
print("Length of the string is:", length)
C1=str.upper()
print("String in uppercase:", C1)
C2=str.lower()
print("String in lowercase:", C2)
c4=str.split()
print("String split into words:", c4)
print(str.startswith("a"))
print(str.endswith("z"))
print(str.find("is"))
print(str.count("i"))
print(str.replace("is", "was"))
print(str.join(["Hello  ", " World"]))