list=[]
for i in range(5):
    n=int(input("Enter the number"))
    list.append(n)
print("The list is ",list)
print(type(list))
list.insert(2,10)
print("After inserting 10 at index 2")
print(list)
list2=[20,30,40]
list.extend(list2)
print("After extending with another list")
print(list)
list.remove(10)
print("After removing 10 from the list")    
print(list)
list.pop()
print("After popping the last element from the list")
print(list)
idx=list.index(30)
print("The index of 30 is ",idx)
count=list.count(20)
print("The count of 20 is ",count)
list.sort()
print("The sorted list is ",list)
list.reverse()
print("The reversed list is ",list)
length=len(list)
print("The length of the list is ",length)  
sum=sum(list)
print("The sum of the list is ",sum)
max=max(list)
print("The maximum element in the list is ",max)
min=min(list)
print("The minimum element in the list is ",min)    
sorted_list=sorted(list)
print("The sorted list using sorted() is ",sorted_list)
